@startuml
interface Print {
	
	PrintWeak()
	PrintStrong()
}

User -> Print: Uses

class PrintBanner {
	PrintWeek()
	PrintStrong()
}

Print <|.. PrintBanner

class Banner {
	ShowWithParen()
	ShowWithAster()
}

PrintBanner -|> Banner


@enduml
