@startuml
interface Printer {
	PrintWeak()
	PrintStrong()
}

User -> Printer: Uses

class PrintBanner {
	PrintWeek()
	PrintStrong()
}

Print <|.. PrintBanner

class Banner {
	ShowWithParen()
	ShowWithAster()
}

PrintBanner -|> Banner


@enduml
